Update S3 configuration format in README
Fix: CRD spec requires an object to configure filer.s3.

Error: `The Seaweed "seaweed-sample" is invalid: spec.filer.s3: Invalid value: "boolean": spec.filer.s3 in body must be of type object: "boolean"`